### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by MagnusOxlund** [iss0/SyncthingTray#27]
Sorry to be asking a dumb question here, but how do I use/install this on Windows? A more comprehensive readme file would be appreciated! Thanks.

**Comment by NickPyz** [comment]
@MagnusOxlund 

I am not the developer, just another user. The latest release is 8 months old, and development is kind of slow here ... but the application meets my needs. 

Syncthing Tray does not contain the main Syncthing executable file. So - if you haven't done so yet, go to syncthing.com and get the executable for your version of Windows (32 or 64 bit). Also, please  note that neither syncthing nor SyncthingTray come with an "installer".

(1) Unzip the Syncthing version and place the files inside a folder named "Syncthing" inside your Program Files (or Program Files (x86) folder.

(2) Execute syncthing.exe, and let it run. If you need assistance with Syncthing configuration, there are documents and an active user forum at the website.

(3) I suggest NOT running SyncthingTray until your Syncthing setup is complete, and you have configured shared folders and devices in the WebGUI - and everything is working correctly.

(4) Download the SyncthingTray version for 32 or 64 bit Windows. Unzip it into a folder called "SyncthingTray" and move this folder into the "Syncthing" folder you created in Step 1. Execute syncthingtray.exe, and let it run.

(5) StTray will open a configuration box. Make sure you have the "Path" pointing to syncthing.exe, and the correct address for the WebGUI (mine is 127.0.0.1:8080). There are other ON / OFF options like Start on Boot, Start Minimized, UPNP, etc ... pretty straight-forward.

(6) Click "Start" button. Syncthing will startup and your WebGUI should open. Clock "STOP" and syncthing shuts down.

Good luck.

**Comment by MagnusOxlund** [comment]
Thank you for taking the time to reply.

I'm new to GitHub and made the mistake of assuming that the repository was what I had to download.

Your reply did help though as it made me realize there was an .exe to look for.

Again, thanks for the help. I appreciate it. Sorry for the inconvenience.
